"""Add positions

Revision ID: d1ffcb5bc5ee
Revises: a7e6f352c9a4
Create Date: 2025-12-10 10:14:08.306180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ffcb5bc5ee'
down_revision = 'a7e6f352c9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('positions')

    # ### end Alembic commands ###
